let S=[],selected=null,cart=[],staff=false,admin=false;
const $=x=>document.getElementById(x);
async function api(path,opt={}){let r=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...opt});let d=await r.json();if(!r.ok)throw Error(d.error||'Server error');return d}
const mins=t=>{let [h,m]=t.split(':').map(Number);return h*60+m},now=()=>{let d=new Date();return d.getHours()*60+d.getMinutes()};
const isOpen=s=>now()>=mins(s.start_time)&&now()<mins(s.end_time);
function active(){return S.find(isOpen)} function next(){let n=now();return [...S].sort((a,b)=>mins(a.start_time)-mins(b.start_time)).find(s=>mins(s.start_time)>n)||S[0]}
async function load(){S=await api('/sessions');if(!selected||!S.some(x=>x.id==selected.id))selected=S[0];renderCustomer();renderSessions();if(staff)renderStaff();if(admin)renderAdmin();if($('display').classList.contains('active'))renderDisplay()}
function renderSessions(){$('sessions').innerHTML=S.map(s=>`<div class="session ${selected?.id==s.id?'sel':''}" onclick="pick(${s.id})"><h3>${s.name}</h3><div>${s.start_time} - ${s.end_time}</div><p class="${isOpen(s)?'open':'closed'}">${isOpen(s)?'🟢 OPEN':'🔒 CLOSED'}</p><small>Prefix: ${s.prefix}</small></div>`).join('')}
window.pick=id=>{selected=S.find(s=>s.id==id);cart=[];renderSessions();renderCustomer()}
function renderCustomer(){let s=selected||active()||S[0];if(!s)return;$('customerPanel').innerHTML=`<h2>${s.name}</h2><p>${s.start_time} - ${s.end_time}</p><p class="${isOpen(s)?'open':'closed'}"><b>${isOpen(s)?'Ordering is OPEN':'Ordering is CLOSED. Opens at '+s.start_time}</b></p><h3>Menu</h3><div class="menu">${s.menu.map((m,i)=>`<label class="food">${m.name}${m.veg?'':' 🥩'} — ₹${m.price}<input type="checkbox" ${cart.some(x=>x.name==m.name)?'checked':''} ${isOpen(s)?'':'disabled'} onchange="toggle(${i})"></label>`).join('')}</div><br><button class="primary" onclick="token()" ${isOpen(s)&&cart.length?'':'disabled'}>Get Token</button>`}
window.toggle=i=>{let m=selected.menu[i],n=cart.findIndex(x=>x.name==m.name);n>=0?cart.splice(n,1):cart.push(m);renderCustomer()}
window.token=async()=>{try{let d=await api('/token',{method:'POST',body:JSON.stringify({session_id:selected.id,items:cart})});$('receipt').classList.remove('hide');$('receipt').innerHTML=`<div class="tokenbox"><h2>Your Token</h2><div class="token">${d.token.number}</div><p>People ahead: ${d.people_ahead} | Estimated wait: ${d.estimated_wait} min</p><button onclick="$('receipt').classList.add('hide')">Close</button></div>`;cart=[];await load()}catch(e){alert(e.message)}}
async function renderDisplay(){let s=active();if(!s){let n=next();$('ds').textContent='Counter Closed';$('now').textContent='--';$('up').innerHTML='';$('dmsg').textContent=n?'Ordering opens at '+n.start_time:'';return}let q=await api('/queue/'+s.id);$('ds').textContent=s.name;$('now').textContent=q.now_serving||'--';$('up').innerHTML=q.waiting.slice(0,4).map(x=>`<span class="next">${x.number}</span>`).join('')||'No waiting tokens';$('dmsg').textContent=`Waiting: ${q.waiting.length} | Served: ${q.served_count}`}
async function renderStaff(){if(!staff)return;let s=active()||selected,q=await api('/queue/'+s.id);$('staffPanel').innerHTML=`<div class="card"><div class="row"><h2>Staff Dashboard</h2><button onclick="staff=false;$('staffLogin').classList.remove('hide');$('staffPanel').classList.add('hide')">Logout</button></div><p>Session: <b>${s.name}</b></p><button class="primary" onclick="callNext(${s.id})">Call Next</button></div><div class="card"><h3>Waiting Queue</h3>${q.waiting.map(t=>`<div class="edit"><b>${t.number}</b> — ${t.items.map(x=>x.name).join(', ')}<br><button onclick="status(${t.id},'READY')">Ready</button> <button onclick="status(${t.id},'SERVED')">Served</button> <button class="danger" onclick="status(${t.id},'SKIPPED')">Skip</button></div>`).join('')||'No waiting tokens'}</div>`}
window.callNext=async id=>{try{await api('/queue/'+id+'/call-next',{method:'POST'});load()}catch(e){alert(e.message)}};window.status=async(id,s)=>{try{await api('/token/'+id+'/status',{method:'POST',body:JSON.stringify({status:s})});load()}catch(e){alert(e.message)}}
async function renderAdmin(){if(!admin)return;let a=await api('/analytics');$('adminPanel').innerHTML=`<div class="card"><div class="row"><h2>Admin Dashboard</h2><button onclick="admin=false;$('adminLogin').classList.remove('hide');$('adminPanel').classList.add('hide')">Logout</button></div><p>Total tokens today: <b>${a.total_tokens}</b></p>${S.map(s=>`<div class="edit"><b>${s.name}</b><br>Start <input id="st${s.id}" value="${s.start_time}"> End <input id="et${s.id}" value="${s.end_time}"><button onclick="saveTime(${s.id})">Save Time</button><hr>${s.menu.map((m,i)=>`<input id="mn${s.id}_${i}" value="${m.name}"><input id="pr${s.id}_${i}" type="number" value="${m.price}">`).join('')}<button onclick="saveMenu(${s.id})">Save Menu</button></div>`).join('')}</div>`}
window.saveTime=async id=>{try{await api('/sessions/'+id,{method:'PUT',body:JSON.stringify({start_time:$('st'+id).value,end_time:$('et'+id).value})});load()}catch(e){alert(e.message)}};window.saveMenu=async id=>{try{let s=S.find(x=>x.id==id),menu=s.menu.map((m,i)=>({name:$('mn'+id+'_'+i).value,price:+$('pr'+id+'_'+i).value,veg:m.veg}));await api('/sessions/'+id,{method:'PUT',body:JSON.stringify({menu})});load()}catch(e){alert(e.message)}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(b.dataset.v).classList.add('active');load()});
$('slogin').onclick=()=>{if($('sp').value==='staff123'){staff=true;$('staffLogin').classList.add('hide');$('staffPanel').classList.remove('hide');renderStaff()}else $('serr').textContent='Wrong password'};
$('alogin').onclick=()=>{if($('ap').value==='admin123'){admin=true;$('adminLogin').classList.add('hide');$('adminPanel').classList.remove('hide');renderAdmin()}else $('aerr').textContent='Wrong password'};
function clock(){$('clock').textContent=new Date().toLocaleTimeString()}setInterval(clock,1000);clock();
(async()=>{try{await api('/health');$('conn').textContent='🟢 Backend connected';await load()}catch(e){$('conn').textContent='🔴 Backend not connected'}})();setInterval(()=>load().catch(()=>{}),5000);